name: food_in_flight

volumes:
  pgdata:
# tar backup: docker run --rm -v pgdata:/dbdata -v $(pwd):/backup alpine tar cvf /backup/backup.tar /dbdata
# untar backup: docker run --rm -v pgdata:/dbdata -v $(pwd):/backup alpine bash -c "cd /dbdata && tar xvf /backup/backup.tar --strip 1"

networks:
  backnet:
    driver: bridge
    internal: true
  frontnet:
    driver: bridge

services:
  foodinflight_frontend:
    container_name: foodinflight_frontend
    build:
      context: .
      dockerfile: configs/Dockerfile_frontend
    ports:
      - "3000:3000"
    networks:
      - backnet

  foodinflight_backend:
    container_name: foodinflight_backend
    depends_on:
      - foodinflight_postgres
    build:
      context: .
      dockerfile: configs/Dockerfile_backend
    volumes:
      - ./foodinflight_backend/media:/app/media
      - ./foodinflight_backend/static:/app/static
      - ./logs:/logs
    ports:
      - "8001:8001"
    networks:
      - backnet

  foodinflight_nginx:
    container_name: foodinflight_nginx
    depends_on:
      - foodinflight_certbot
    image: nginx:alpine
    volumes:
      - ./configs/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./configs/uwsgi_params:/etc/nginx/uwsgi_params
      - ./foodinflight_backend/media:/web/media
      - ./foodinflight_backend/static:/web/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./logs:/logs
    environment:
      - NGINX_HOST=${HOST_DOMAIN}
      - DEPLOYER_HOSTNAME=foodinflight_deployer
      - BACKEND_HOSTNAME=foodinflight_backend
      - FRONTEND_HOSTNAME=foodinflight_frontend
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
    entrypoint: /docker-entrypoint.sh
    command: >
      /bin/sh -c " while :; do sleep 6h & wait $${!}; nginx -s reload; done & /docker-entrypoint.sh nginx -g \"daemon off;\""
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backnet
      - frontnet

  foodinflight_tgbot:
    container_name: foodinflight_tgbot
    depends_on:
      - foodinflight_postgres
    build:
      context: .
      dockerfile: configs/Dockerfile_tgbot
    networks:
      - backnet

  foodinflight_certbot:
    container_name: foodinflight_certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  foodinflight_postgres:
    container_name: foodinflight_postgres
    image: postgres:alpine
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: "${POSTGRES_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data            # docker volume usage
      - ./configs/postgresql.conf:/etc/postgresql.conf
      - ./logs:/logs
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - backnet

    foodinflight_deployer:
      container_name: foodinflight_deployer
      build:
        context: webhook-deployer
        dockerfile: webhook-deployer/Dockerfile
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./:/repo/
        - ~/.ssh/:/root/.ssh/
      ports:
        - "80:80"
      networks:
        - backnet
