version: '3.7'

volumes:
  pgdata:

services:
  foodinflight_backend_dev:
    container_name: foodinflight_backend_dev
    depends_on:
      - foodinflight_postgres_dev
    build:
      context: .
      dockerfile: configs/Dockerfile_backend_dev
    volumes:
      - ./foodinflight_backend/media:/app/media
      - ./foodinflight_backend/static:/app/static
      - ./logs:/logs
    ports:
      - "8000:8000"

  foodinflight_postgres_dev:
    container_name: foodinflight_postgres_dev
    image: postgres:alpine
    command:
      - "postgres -c config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: "${POSTGRES_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data            # docker volume usage
      - ./configs/postgresql.conf:/etc/postgresql.conf
      - ./logs:/logs
    ports:
      - "5432:5432"
